### ISSUE TITLE
New update breaks counsel-find-file in ivy

### ISSUE THREAD

**Issue by CSRaghunandan** [nflath/hungry-delete#27]
Here's how you can reproduce the bug:
* open `counsel-find-file`
* press `C-n` `C-p` or `up` `down` keys any number of times
* press `C-h` or `backspace`(`delete` if you're on mac) and ivy shouts: `Text is readonly`

Note: This bug only happens when we try to go up a directory by pressing `C-h` or `backspace` or `delete`(if you're on mac).

**Comment by nflath** [comment]
Should be fixed now.

**Comment by CSRaghunandan** [comment]
Thanks for the quick fix 👍

**Comment by rakanalh** [comment]
This is still an issue for me:
```
(use-package hungry-delete
  :config
  (global-hungry-delete-mode))
```

And I get text is read only error

**Comment by CSRaghunandan** [comment]
@nflath @rakanalh Oh yes, I can confirm the bug is still present.

**Comment by nflath** [comment]
OK i think it actually works this time - can you try again?

**Comment by CSRaghunandan** [comment]
@nflath I do not see any updates to hungry-delete via MELPA.

meanwhile, I found a workaround for this problem. Turn off `hungry-delete-mode` in `minibuffer-setup-hook`

**Comment by nflath** [comment]
Yeha, hand't pushed, I think.   Should be done now(at least on github and I pushed the tags).  Sorry!

**Comment by rakanalh** [comment]
after upgrading, the issue is no longer there. Thanks for fixing

**Comment by markgdawson** [comment]
I'm seeing these same issue again after upgrading to using the native comp build of Emacs:

GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)

**Comment by lkzz** [comment]
> I'm seeing these same issue again after upgrading to using the native comp build of Emacs:
> 
> GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.24, cairo version 1.16.0)
me too!

**Comment by markgdawson** [comment]
The solution from @CSRaghunandan  worked for me, adding the following code:
```
(add-hook 'minibuffer-setup-hook (lambda () (hungry-delete-mode -1)))
```

**Comment by seagle0128** [comment]
Adding `minibuffer-mode` to `hungry-delete-except-modes` works for me as well.
